apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tf-ps0
spec:
  replicas: 1
  template:
    metadata:
      labels:
        tf-ps: "0"
        name-prefix: "tf"
        job: "ps"
    spec:
      containers:
      - name: tf-ps0
        image: gcr.io/tensorflow/tensorflow
        ports:
        - containerPort: 6006
          name: tensorboard
        - containerPort: 2222
          name: grpcport
        env: []
        volumeMounts:
        - mountPath: /joy
          name: shared
        - mountPath: /imagenetdata
          name: imagenet
      nodeSelector:
        nodedesc: cpunode0
      volumes:
      - name: shared
        hostPath:
          path: /home/joyadmin
      - name: imagenet
        hostPath:
          path: /mnt/imagenet-data
---
apiVersion: v1
kind: Service
metadata:
  name: tf-ps0
  labels:
    tf-ps: "0"
spec:
  type:  ClusterIP
  ports:
  - name: tensorboard
    port: 6006
  - name: grpcport
    port: 2222
  selector:
    tf-ps: "0"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tf-ps1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        tf-ps: "1"
        name-prefix: "tf"
        job: "ps"
    spec:
      containers:
      - name: tf-ps1
        image: gcr.io/tensorflow/tensorflow
        ports:
        - containerPort: 6006
          name: tensorboard
        - containerPort: 2222
          name: grpcport
        env: []
        volumeMounts:
        - mountPath: /joy
          name: shared
        - mountPath: /imagenetdata
          name: imagenet
      nodeSelector:
        nodedesc: cpunode1
      volumes:
      - name: shared
        hostPath:
          path: /home/joyadmin
      - name: imagenet
        hostPath:
          path: /mnt/imagenet-data
---
apiVersion: v1
kind: Service
metadata:
  name: tf-ps1
  labels:
    tf-ps: "1"
spec:
  type:  ClusterIP
  ports:
  - name: tensorboard
    port: 6006
  - name: grpcport
    port: 2222
  selector:
    tf-ps: "1"
---
