apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tf-worker0
spec:
  replicas: 1
  template:
    metadata:
      labels:
        tf-worker: "0"
        name-prefix: "tf"
        job: "worker"
    spec:
      containers:
      - name: tf-worker0
        image: gcr.io/tensorflow/tensorflow:latest-gpu
        ports:
        - containerPort: 6006
          name: tensorboard
        - containerPort: 2222
          name: grpcport
        resources:
          limits:
            alpha.kubernetes.io/nvidia-gpu: 4
        volumeMounts:
        - mountPath: /usr/local/nvidia
          name: nvidia-driver
        - mountPath: /joy
          name: shared
        - mountPath: /imagenetdata
          name: imagenet
      volumes:
      - name: nvidia-driver
        hostPath:
          path: /opt/nvidia-driver/current
      - name: shared
        hostPath:
          path: /home/joyadmin
      - name: imagenet
        hostPath:
          path: /mnt/imagenet-data
---
apiVersion: v1
kind: Service
metadata:
  name: tf-worker0
  labels:
    tf-worker: "0"
spec:
  type:  ClusterIP
  ports:
  - name: tensorboard
    port: 6006
  - name: grpcport
    port: 2222
  selector:
    tf-worker: "0"
---