apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tf-worker1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        tf-worker: "1"
        name-prefix: "tf"
        job: "worker"
    spec:
      containers:
      - name: tf-worker1
        image: gcr.io/tensorflow/tensorflow:1.2.0-gpu
        ports:
        - containerPort: 6006
          name: tensorboard
        - containerPort: 2222
          name: grpcport
        resources:
          limits:
            alpha.kubernetes.io/nvidia-gpu: 4
        volumeMounts:
        - mountPath: /usr/local/nvidia
          name: nvidia-driver
        - mountPath: /joy
          name: shared
        - mountPath: /imagenetdata
          name: imagenet
        - mountPath: /imagenetazurefiles
          name: imagenetazure
      volumes:
      - name: nvidia-driver
        hostPath:
          path: /opt/nvidia-driver/current
      - name: shared
        hostPath:
          path: /home/joyadmin
      - name: imagenet
        hostPath:
          path: /mnt/imagenet-data
      - name: imagenetazure
        azureFile:
          secretName: azure-secret
          shareName: imagenet
          readOnly: false
---
apiVersion: v1
kind: Service
metadata:
  name: tf-worker1
  labels:
    tf-worker: "1"
spec:
  type:  ClusterIP
  ports:
  - name: tensorboard
    port: 6006
  - name: grpcport
    port: 2222
  selector:
    tf-worker: "1"
---